[project]
name = "nonebot-plugin-whateat-pic"
version = "1.0.1"
description = "基于Nonebot2的今天吃什么（离线版）"
authors = [{name="Camilia",email="1141538825@qq.com"}]
license = {text = "MIT"}
dependencies = ["nonebot2>=2.0.0rc1", "nonebot-adapter-onebot>=2.1.3", "httpx>=0.23.0", "Pillow<10.0.0,>=9.2.0", "tortoise-orm[aiosqlite]>=0.19.2"]
requires-python = ">=3.7"
readme = "README.md"
[project.urls]
"Homeoage" = "https://github.com/Cvandia/nonebot-plugin-whateat-pic"
"Bug Tracker" = "https://github.com/Cvandia/nonebot-plugin-whateat-pic/issues"
