[tool.poetry]
name = "nonebot-plugin-whateat-pic"
version = "1.0.6"
description = "基于Nonebot2的今天吃什么（离线版）"
authors = ["Cvandia"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/Cvandia/nonebot-plugin-whateat-pic"
repository = "https://github.com/Cvandia/nonebot-plugin-whateat-pic"

[tool.poetry.dependencies]
python = ">=3.8,<4"
nonebot2 = ">=2.0.0-beta.1"
nonebot-adapter-onebot = ">=2.0.0-beta.1"
httpx = ">=0.19.0"
aiofiles = ">=0.7.0"
pydantic = ">=1.10.2"

[tool.poetry.dev-dependencies]
nb-cli = "^0.6.0"
black = "^22.1.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"